from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.login, name='login'),
    path('admin', views.admin, name='admin'),
    path('user', views.usertemplate, name='usertemplate'),
    path('muncipality_home', views.muncipality_home, name='muncipality_home'),
    path('driver_home', views.driver_home, name='driver_home'),
    path('harithakarma_home', views.harithakarma_home, name='harithakarma_home'),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('muncipal_reg', views.Muncipality_Reg, name='muncipal_reg'),
    path('public_reg', views.Public_Reg, name='public_reg'),
    path('harithakarma_reg', views.Harithakarma_Reg, name='harithakarma_reg'),
    path('driver_reg', views.Driver_Reg, name='driver_reg'),
    path('muncipality_adminview', views.muncipality_adminview, name='muncipality_adminview'),
    path('public_adminview', views.public_adminview, name='public_adminview'),
    path('harithakarma_adminview', views.harithakarma_adminview, name='harithakarma_adminview'),
    path('driver_adminview', views.driver_adminview, name='driver_adminview'),
    path('muncipality_update', views.muncipality_update, name='muncipality_update'),
    path('public_update', views.public_update, name='public_update'),
    path('harithakarma_update', views.harithakarma_update, name='harithakarma_update'),
    path('driver_update', views.driver_update, name='driver_update'),
    path('driver_muncipality_view', views.driver_muncipality_view, name='driver_muncipality_view'),
    path('muncipality_user_view', views.muncipality_user_view, name='muncipality_user_view'),
    path('apply_dustbin', views.Dustbin_Reg, name='apply_dustbin'),
    path('payment/<int:logindata>/<int:amount>', views.payment, name='payment'),
    path('muncipality_payment_view', views.muncipality_payment_view, name='muncipality_payment_view'),
    path('account', views.account, name='account'),
    path('dustbin_user_view', views.dustbin_user_view, name='dustbin_user_view'),
    path('dustbin_details_update/<int:id>', views.dustbin_update, name='dustbin_details_update'),
    path('dustbin_details_delete/<int:id>', views.dustbin_details_delete, name='dustbin_details_delete'),
    path('public_dustbin_reg', views.Public_Dustbin_Reg, name='public_dustbin_reg'),
    path('public_dustbin_view', views.public_dustbin_view, name='public_dustbin_view'),
    path('public_dustbin_update/<int:id>', views.public_dustbin_update, name='public_dustbin_update'),
    path('public_dustbin_delete/<int:id>', views.public_dustbin_delete, name='public_dustbin_delete'),
    path('dustbin_public_search', views.dustbin_public_search, name='dustbin_public_search'),
    path('wasteupdates/<int:id>', views.wasteupdates, name='wasteupdates'),
    path('totalwaste/<int:id>', views.totalwaste, name='totalwaste'),
    path('muncipality_waste_notifications', views.muncipality_waste_notifications, name='muncipality_waste_notifications'),
]
    