# Generated by Django 5.1.4 on 2025-01-17 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('usertype', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarithakarmaReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harithakarma_id', models.CharField(max_length=100, unique=True)),
                ('muncipality', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='DriverRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact_no', models.IntegerField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loginid', to='swmapp.logintable')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municiplaityid', to='swmapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='MuncipalityReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muncipality_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('thaluk', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='PublicReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('rationcard_no', models.IntegerField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.logintable')),
                ('muncipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.muncipalityreg')),
            ],
        ),
    ]
