# Generated by Django 5.1.4 on 2025-01-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverRegister',
            new_name='DriverReg',
        ),
    ]
