# Generated by Django 5.1.4 on 2025-01-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0002_rename_driverregister_driverreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicreg',
            name='muncipality',
        ),
    ]
