# Generated by Django 5.1.4 on 2025-01-17 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0003_remove_publicreg_muncipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicreg',
            name='muncipality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mu', to='swmapp.logintable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicreg',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='swmapp.logintable'),
        ),
    ]
