# Generated by Django 5.1.4 on 2025-01-17 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0004_publicreg_muncipality_alter_publicreg_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicreg',
            name='muncipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.muncipalityreg'),
        ),
    ]
