# Generated by Django 5.1.4 on 2025-02-01 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0005_alter_publicreg_muncipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverreg',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.muncipalityreg'),
        ),
    ]
