# Generated by Django 5.1.4 on 2025-02-01 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0006_alter_driverreg_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='DustbinReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_category', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('muncipality', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.logintable')),
            ],
        ),
    ]
