# Generated by Django 5.1.4 on 2025-02-02 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0007_dustbinreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('cvv', models.IntegerField()),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.logintable')),
            ],
        ),
    ]
