# Generated by Django 5.1.4 on 2025-02-02 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='dustbin_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='swmapp.dustbinreg'),
            preserve_default=False,
        ),
    ]
