# Generated by Django 5.1.4 on 2025-02-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0009_payment_dustbin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='dustbinreg',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
