# Generated by Django 5.1.4 on 2025-02-07 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0010_remove_payment_status_dustbinreg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dustbinreg',
            name='muncipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.muncipalityreg'),
        ),
    ]
