# Generated by Django 5.1.4 on 2025-02-07 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0011_alter_dustbinreg_muncipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicreg',
            name='login_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='swmapp.logintable'),
        ),
    ]
