# Generated by Django 5.1.4 on 2025-02-07 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0012_alter_publicreg_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=50)),
                ('card_no', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('bank_balance', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dustbinreg',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public', to='swmapp.logintable'),
        ),
    ]
