# Generated by Django 5.1.4 on 2025-02-13 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0013_account_alter_dustbinreg_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public_Dustbin_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dustbin_id', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.logintable')),
            ],
        ),
    ]
