# Generated by Django 5.1.4 on 2025-02-14 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0015_wasteupdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteupdates',
            name='dustbin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_enteries', to='swmapp.public_dustbin_register'),
        ),
    ]
