# Generated by Django 5.1.4 on 2025-02-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0016_alter_wasteupdates_dustbin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteupdates',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
