# Generated by Django 5.1.4 on 2025-02-27 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0019_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.publicreg'),
        ),
    ]
