# Generated by Django 5.1.4 on 2025-02-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0020_alter_complaints_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
