# Generated by Django 5.1.4 on 2025-02-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0021_logintable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='reply',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
