# Generated by Django 5.1.4 on 2025-02-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0022_complaints_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicreg',
            name='contact_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='publicreg',
            name='rationcard_no',
            field=models.IntegerField(unique=True),
        ),
    ]
