# Generated by Django 5.1.4 on 2025-03-01 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0024_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('dustbin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.dustbinreg')),
                ('harithakarma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swmapp.harithakarmareg')),
            ],
        ),
    ]
