# Generated by Django 5.1.4 on 2025-03-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0025_wastecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbinreg',
            name='collection_status',
            field=models.IntegerField(default=0),
        ),
    ]
