# Generated by Django 5.1.4 on 2025-03-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmapp', '0027_remove_public_dustbin_register_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
